dist: trusty
language: rust
services: docker
sudo: required
rust:
- nightly

env:
  global:
    - CRATE_NAME=qrsync

matrix:
  include:
    # Linux
    - env: TARGET=x86_64-unknown-linux-gnu 
    - env: TARGET=x86_64-unknown-linux-gnu
    - env: TARGET=aarch64-unknown-linux-gnu DISABLE_TESTS=1
    - env: TARGET=aarch64-unknown-linux-musl DISABLE_TESTS=1
    - env: TARGET=arm-unknown-linux-gnueabi DISABLE_TESTS=1
    - env: TARGET=armv7-unknown-linux-gnueabihf DISABLE_TESTS=1

    # OSX
    - env: TARGET=x86_64-apple-darwin
      os: osx

    # Windows
    - env: TARGET=x86_64-pc-windows-gnu DISABLE_TESTS=1

before_install:
  - set -e
  - rustup self update

install:
  - sh ci/install.sh
  - source ~/.cargo/env || true

script:
  - bash ci/script.sh

after_script: set +e

before_deploy:
  - sh ci/before_deploy.sh

deploy:
  provider: releases
  api_key:
    secure: pcZCbpaCIWrTjVY+rgo25bc5kcp9nSR8f/+ozdBCrmT+gf3N/2kJVJMoxJnX+ymUeuET5F9RpP3nn9K6nJyaYSuTgUYdkZ/VhaOqCvCc+DIjETipwRPstXD7OaFst2gXYMFake8IadGymD2A6+uZnk1N+RC2FkWtbOqtHbZa7tUBryFhTffGEfKaVGrp8RhXe8sjqXq0CcJko8sohUd5xCCh31o/rweJp8sRXoLyaB4Z/toYWEM713ZBcFKhlBdFcvSM07/VsEdFk3Ku8Z9M8vGtql2a2ISyNmVVckdgetx4hm5i8D9KnPJs4KMZNqR8NtBOnosHN2FyiadhXnMxiKCHWH0U2aXDTafkOwZxza/fPxwcw2lyA6FS9lMZkVQayB9RLW8hL6/zJF99WQsgAX97pkIkbuzImnUM+ZEBNJVLplA1D3TE9/9bOlzVBGqrOqGkywKDExXfNTUQNXBCUCuyovYtzvtMzmFVTXIlgdXsfgokFdEE5Obo/eu973m80YDhZcNPrjDdY2NwDL7+mZuMM36lie4YJNzUMQlDDiYDmjrxW2Y8liPw9C9816/j/zYYrvNIvCiqCcMvpG1v8otBBoH37KtKsLD4ZVsEhkpTThylLN1pJhzhbnU0IsEMJ1XmVhR4s7jxcWBOI/0qJDwtoxf/XnTfnTfkYsrKrt4=
  file_glob: true
  file: $CRATE_NAME-$TRAVIS_TAG-$TARGET.*
  on:
    repo: crisidev/qrsync
    tags: true
  skip_cleanup: 'true'

cache: cargo
before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

branches:
  only:
    # release tags
    - /^v\d+\.\d+\.\d+.*$/
    - master

notifications:
  email:
    on_success: never
  irc:
    channels:
      - "chat.freenode.net#crisidev"
    on_success: always # default: always
    on_failure: always # default: always
    use_notice: true
