[package]
name = "qrsync"
version = "0.1.8"
authors = ["Matteo Bigoi <bigo@crisidev.org>"]
description = "Utility to copy files over WiFi to/from mobile devices inside a terminal."
documentation = "https://docs.rs/qrsync"
readme = "README.md"
homepage = "https://github.com/crisidev/qrsync"
repository = "https://github.com/crisidev/qrsync"
license = "MIT"
keywords = ["qrcode", "terminal", "rocket", "mobile"]
categories = ["command-line-utilities", "multimedia"]
edition = "2021"

[dependencies]
base64 = "0"
ctrlc = { version = "3", features = ["termination"] }
clap = { version = "3", features = ["derive"] }
log = "0.4"
pnet = "0.29"
pretty_env_logger = "0.4"
qr2term = "0.3"
rocket = "0.4.10"
rocket_contrib = "0.4.10"
rocket-download-response = "0.4"
rocket-multipart-form-data = "0.8"
thiserror = "1.0"

[dev-dependencies]
pretty_assertions = "1.2"

[[bin]]
name = "qrsync"
